version: "3.7"
services:
  tortoisebot-ros2-gazebo:
    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile.tortoisebot-ros2-gazebo
    image: chatzialex/cp22:tortoisebot-ros2-gazebo
    container_name: tortoisebot-ros2-gazebo_1
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - ros2-network
  tortoisebot-ros2-slam:
    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile.tortoisebot-ros2-slam
    image: chatzialex/cp22:tortoisebot-ros2-slam
    container_name: tortoisebot-ros2-slam_1
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - ros2-network

networks:
  ros2-network: